### ISSUE TITLE
最新更新的版本，使用react发现报错，而且非全屏没有显示全，是需要新的使用方法吗

### ISSUE THREAD

**Issue by xiongmao-f** [995231030/autofit.js#10]

**Comment by LarryZhu-dev** [comment]
你好，经查证，旧版会有这个问题，深感抱歉，目前的最新版本已经完全兼容react了

**Comment by xiongmao-f** [comment]
大佬辛苦了，当时是我没仔细看更新log，感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LarryZhu-dev/autofit.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月31日(星期四) 下午5:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [LarryZhu-dev/autofit.js] 最新更新的版本，使用react发现报错，而且非全屏没有显示全，是需要新的使用方法吗 (Issue #10)





 
你好，经查证，旧版会有这个问题，深感抱歉，目前的最新版本已经完全兼容react了
