### ISSUE TITLE
【bug】currelRectification参数未赋值

### ISSUE THREAD

**Issue by libwiki** [995231030/autofit.js#11]
currelRectification参数未赋值导致空选择器
在off方法中调用的```document.querySelectorAll(currelRectification)```中并未用到传入的el参数也，会报错```Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': The provided selector is empty.
    at <anonymous>:1:27```

**Comment by 995231030** [comment]
如果在调用autofit.init()之前使用.off()是有可能出现这个错误的，如果按照正常步骤使用autofit，还请贴下代码，说明下复现步骤，感谢

**Comment by libwiki** [comment]
```
<script setup>
import autofit from "autofit.js";

</script>

<template>
  <div>
    <button @click="autofit.init({el: `#app`})">开启</button>
    <button @click=" autofit.off('#app')">关闭</button>
  </div>
</template>
```
<img width="591" alt="image" src="https://github.com/995231030/autofit.js/assets/30712221/de4fea79-c545-40bd-9653-0e630a3dc77e">

**Comment by 995231030** [comment]
此问题已修复
