### ISSUE TITLE
你好，大屏页面使用后，跳转到其他页面后，#app设置的效果还在，页面不能滚动下滑

### ISSUE THREAD

**Issue by liutingfenga** [995231030/autofit.js#2]

**Comment by 995231030** [comment]
是的，设置是全局的，如果其他页面需要滚动，可以在其他页面内部的容器中设置滚动

**Comment by liutingfenga** [comment]
虽然但是，刷新页面就没有了。可以加个解除方法，在大屏页面注销前，把这个自适应解除，就很优雅。这我不能每个页面都手动设置下滑动。

**Comment by 995231030** [comment]
收到反馈，下个版本会考虑解除的方法。

**Comment by 995231030** [comment]
v2.0.0版本新增解除事件：
使用：
`autofit.off()`
或
`autofit.off("#app")`
