### ISSUE TITLE
类型出错，可选参数还是要必传

### ISSUE THREAD

**Issue by SoleilQ** [995231030/autofit.js#8]
<img width="821" alt="image" src="https://github.com/995231030/autofit.js/assets/20468482/a26e17ad-cf9c-4327-a811-84bfc68ccdd3">

**Comment by 995231030** [comment]
请问哪个参数出错了

**Comment by SoleilQ** [comment]
> 请问哪个参数出错了

```ts
autofit.init(); // ts会提示应有一个参数
```
<img width="771" alt="image" src="https://github.com/995231030/autofit.js/assets/20468482/773cb40f-70a6-4d4b-8be7-0fb61a7e050b">


```ts
autofit.init({
      designHeight: 1080,
      designWidth: 1920,
      renderDom:"#app",
      resize: true
  },false);

// 1. options里面的值都是要必传的，而非文档里面说的是可选
// 2. 没有false这个参数
```

<img width="428" alt="image" src="https://github.com/995231030/autofit.js/assets/20468482/4926e655-c290-4a87-a9d8-5e04f98b91ee">

**Comment by 995231030** [comment]
用ts的话需要传一个空的js对象即`{}`
