### ISSUE TITLE
你好，我在使用时，发现留白，是使用方式不对吗

### ISSUE THREAD

**Issue by 15738039217** [995231030/autofit.js#9]

**Comment by 15738039217** [comment]
![截屏2023-06-13 上午11 48 31](https://github.com/995231030/autofit.js/assets/17919082/47fc5f15-a58c-4ff1-8fac-bbd4452515a2)

**Comment by 15738039217** [comment]
浏览器比例是1920*1080，我的大屏设计稿是1920*1080,页面布局有头部导航，tag, 还有最顶部的浏览器的菜单，   autofit.init({
      designHeight: 920 - 82,
      designWidth: 1920,
      renderDom: '#screen',
      resize: true
    })

**Comment by 995231030** [comment]
加我QQ吧😅：995231030
